# Generated by Django 2.2.7 on 2020-08-08 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('fecha', models.DateField(max_length=20)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=9)),
                ('condicion', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('tamaño', models.CharField(max_length=10)),
                ('comentario', models.CharField(max_length=150)),
                ('tipoSubasta', models.CharField(max_length=150)),
                ('fotoProd', models.ImageField(upload_to='ImagenesProducto')),
                ('precio', models.CharField(max_length=150)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
