# Generated by Django 2.2.7 on 2020-07-28 01:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registro',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
