# Generated by Django 3.0.6 on 2020-07-30 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20200727_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=9)),
                ('condicion', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('tamaño', models.CharField(max_length=10)),
                ('comentrio', models.CharField(max_length=150)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
